name: resume-scanner

services:
  app:
    build:
      context: .
    image: n1v3x/resume-scanner
    depends_on:
      - redis
    ports:
      - 8000:80
    env_file: .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:latest
    ports:
      - 6379:6379